**WORKING WITH CSV** **FILES**



In [ ]:
import numpy as np
new_data=np.random.random((50,5)) # Generating 50 rows and 5 columns

In [ ]:
print(new_data)

[[1.27123454e-02 8.54213614e-01 1.36670984e-02 7.34480018e-01
  4.05132532e-02]
 [3.69581926e-01 4.97643113e-01 6.14549297e-01 1.93495036e-01
  3.51853311e-01]
 [7.41929870e-02 8.19661440e-01 2.04902393e-01 2.21487229e-01
  1.32415719e-01]
 [4.11916083e-01 4.21998696e-01 5.78705918e-01 6.87841072e-01
  1.81751329e-01]
 [3.01323555e-01 3.95414248e-02 6.00043619e-01 9.38847136e-01
  1.49926056e-01]
 [6.18075891e-01 1.61488129e-01 1.67820359e-01 4.37201405e-01
  1.77837669e-02]
 [4.43247609e-01 5.23305880e-01 1.06357368e-01 7.19662454e-01
  5.56270233e-01]
 [2.29956935e-01 7.86572809e-01 4.44717197e-01 7.49378385e-01
  8.71972674e-01]
 [5.65473872e-01 8.23517650e-01 5.17296259e-02 3.81645248e-01
  7.11361837e-01]
 [1.79838341e-01 2.59114345e-01 4.70133126e-01 7.49770539e-01
  9.68054275e-01]
 [6.90712330e-01 5.87935951e-01 9.07541570e-01 3.26070441e-01
  9.85972421e-01]
 [4.27305303e-02 1.93703668e-01 2.90884225e-01 7.81217342e-01
  1.82033343e-01]
 [8.66184420e-01 8.20952095e-01 5.073505

In [ ]:
np.savetxt("main.csv", new_data, fmt ="%.2f", delimiter= "," ,header="h1,h2,h3,h4,h5")

In [ ]:
read_csv=np.loadtxt("main.csv",delimiter="," )  # Read CSV file
read_csv[0:5:]

array([[0.11, 0.56, 0.34, 0.6 , 0.13],
       [0.09, 0.81, 0.04, 0.96, 0.74],
       [0.97, 0.09, 0.76, 0.44, 0.3 ],
       [0.37, 0.62, 0.58, 0.19, 0.97],
       [0.41, 0.92, 0.72, 0.94, 0.07]])

In [ ]:
print(read_csv)

[[0.11 0.56 0.34 0.6  0.13]
 [0.09 0.81 0.04 0.96 0.74]
 [0.97 0.09 0.76 0.44 0.3 ]
 [0.37 0.62 0.58 0.19 0.97]
 [0.41 0.92 0.72 0.94 0.07]
 [0.03 0.6  0.68 0.65 0.52]
 [0.74 0.71 0.8  0.36 0.32]
 [0.89 0.18 0.75 0.91 0.03]
 [0.72 0.6  0.85 0.72 0.31]
 [0.19 0.64 0.95 0.6  0.61]
 [0.55 0.44 0.52 0.49 0.47]
 [0.57 0.09 0.56 0.49 0.65]
 [0.1  0.75 0.82 0.03 0.24]
 [0.19 0.27 0.9  0.63 0.79]
 [0.3  0.66 0.31 0.04 0.02]
 [0.29 0.53 0.46 0.86 0.07]
 [0.35 0.75 0.95 0.05 0.9 ]
 [0.46 0.35 0.66 0.16 0.86]
 [0.86 0.21 0.87 0.18 0.47]
 [0.16 0.24 0.94 0.55 0.47]
 [0.87 0.56 0.77 0.51 0.29]
 [0.56 0.48 0.65 0.79 0.56]
 [0.31 0.7  0.46 0.95 0.21]
 [0.47 0.31 0.78 0.78 0.03]
 [0.63 0.75 0.91 0.65 0.65]
 [0.88 0.13 0.52 0.95 0.04]
 [0.15 0.86 0.55 0.85 0.41]
 [0.81 0.03 0.7  0.62 0.9 ]
 [0.98 0.69 0.94 0.99 0.46]
 [0.69 0.42 0.1  0.1  0.25]
 [0.99 0.43 0.47 0.11 0.39]
 [0.5  0.03 0.11 0.51 0.33]
 [0.98 0.08 0.38 0.23 0.23]
 [0.48 0.89 0.83 0.77 0.73]
 [0.62 0.06 0.32 0.73 0.11]
 [0.17 0.45 0.69 0.1

**WORKING WITH PICKEL FILE**

In [ ]:
import pickle

In [ ]:
order={"First": 1,"Second" :2, "Third": 3,"Fourth": 4} #write to a pickle file
pickle.dump(order, open("new.pkl", "wb"))

In [ ]:
reading_pickel = pickle.load(open("new.pkl","rb")) # read from pickel file

In [ ]:
reading_pickel

{'First': 1, 'Second': 2, 'Third': 3, 'Fourth': 4}

**WORKING** **WITH JSON FILE**

In [ ]:
import json
collage ={
    "collage" : "Engineering",
    "Objective" : "Electrical Engineering and Computer Science Engineering",
    "departments" : {
        "dept 1" : "Electrical",
        "dept 2" : "Computer"
    },

    "year":[
       "year 1",
       "year 2",
       "year 3",
       "year 4"
    ],
    "number":[1,2,3,4,5],
    "ID":[10,20,30,40]
         }

In [ ]:
 json.dump(collage,open("collage.json","w"))

In [ ]:
print(collage)

{'collage': 'Engineering', 'Objective': 'Electrical Engineering and Computer Science Engineering', 'departments': {'dept 1': 'Electrical', 'dept 2': 'Computer'}, 'year': ['year 1', 'year 2', 'year 3', 'year 4'], 'number': [1, 2, 3, 4, 5], 'ID': [10, 20, 30, 40]}


In [ ]:
new_collage = json.load(open("collage.json","r"))

In [ ]:
new_collage

{'collage': 'Engineering',
 'Objective': 'Electrical Engineering and Computer Science Engineering',
 'departments': {'dept 1': 'Electrical', 'dept 2': 'Computer'},
 'year': ['year 1', 'year 2', 'year 3', 'year 4'],
 'number': [1, 2, 3, 4, 5],
 'ID': [10, 20, 30, 40]}